# Edge TLS via OpenShift router (HTTPS outside, HTTP to pods)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rhbk-kc
  namespace: rhbk-kubeping
spec:
  host: keycloak-kubeping.apps-crc.testing
  to:
    kind: Service
    name: rhbk-kc-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
